Added list of knowledge articles to response page
DEFRA/coreai-mcu-frontend pull request #18
Opened 2024-04-05 14:27 UTC by alistairknight

# **What this PR does / why we need it**:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests
- [ ] Version number in **package.json** has been updated

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-04-05 15:49 UTC, sfitz42 requested changes
Just a few small things.

2024-04-05 16:10 UTC, alistairknight commented on app/config/api.js
> +    baseUrl: process.env.KNOWLEDGE_API_BASE_URL
Added

2024-04-05 16:10 UTC, alistairknight commented on app/routes/document-configure-response.js
> +      const knowledge = await getAllKnowledge('')
Sorted

2024-04-05 16:10 UTC, alistairknight commented on app/views/document-configure-response.njk
> +        {% for k in knowledge %}
Great point

2024-04-08 09:29 UTC, sfitz42 approved these changes
LGTM

2024-04-08 09:47 UTC, merged