Add citations
DEFRA/coreai-mcu-frontend pull request #24
Opened 2024-04-08 15:30 UTC by steve-dickinson

# **What this PR does / why we need it**:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests
- [ ] Version number in **package.json** has been updated

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-04-08 15:39 UTC, sfitz42 requested changes
Looks good. Just a few comments

2024-04-08 15:39 UTC, sfitz42 commented on app/routes/document-citations.js
> +      return h.view('document-citations', { docId, citations }).code(201)
Should be 200 ;)

2024-04-08 15:39 UTC, sfitz42 commented on app/views/document-citations.njk
> +          <h3 class="govuk-heading-s">From line {{ content.loc.lines.from }} to line {{ content.loc.lines.to }} in {{citation.fileName}}</h3>
I would maybe check that the line prop exists here. Just in case

2024-04-08 15:39 UTC, sfitz42 commented on app/routes/document-citations.js
> +      responses.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))
Not sure if we need this here? All responses should be sorted in desc order anyways from the API.

2024-04-09 08:49 UTC, sfitz42 approved these changes

2024-04-09 08:51 UTC, alistairknight approved these changes

2024-04-09 08:51 UTC, merged